- type: job
  id: PrivateInvestigator
  name: job-name-private-investigator
  description: job-description-private-investigator
  playTimeTracker: JobPrivateInvestigator
  startingGear: PrivateInvestigatorGear
  icon: "JobIconPrivateInvestigator"
  supervisors: job-supervisors-hop
  access:
  - Maintenance
  - Service

- type: startingGear
  id: PrivateInvestigatorGear
  equipment:
    id: PrivateInvestigatorPDA
    ears: ClothingHeadsetService
