- type: job
  id: SeniorEngineer
  name: job-name-senior-engineer
  description: job-description-senior-engineer
  playTimeTracker: JobSeniorEngineer
  requirements:
    - !type:OverallPlaytimeRequirement
      time: 7200 #2 hrs
  startingGear: SeniorEngineerGear
  icon: "JobIconSeniorEngineer"
  supervisors: job-supervisors-ce
  access:
  - Maintenance
  - Engineering
  - External
  - Atmospherics

- type: startingGear
  id: SeniorEngineerGear
  equipment:
    head: ClothingHeadHatBeretEngineering
    jumpsuit: ClothingUniformJumpsuitSeniorEngineer
    back: ClothingBackpackEngineeringFilled
    shoes: ClothingShoesBootsWork
    id: SeniorEngineerPDA
    eyes: ClothingEyesGlassesMeson
    belt: ClothingBeltUtilityEngineering
    ears: ClothingHeadsetEngineering
  innerClothingSkirt: ClothingUniformJumpskirtSeniorEngineer
  satchel: ClothingBackpackSatchelEngineeringFilled
  duffelbag: ClothingBackpackDuffelEngineeringFilled
